### ISSUE TITLE
Is this a fork of rust-igc?

### ISSUE THREAD

**Issue by estk** [Joey9801/igc-rs#1]
Looking at https://github.com/Turbo87/rust-igc, it seems like this may be a fork of https://github.com/Turbo87/rust-igc, is that true?

**Comment by Joey9801** [comment]
This is not a fork of anything.

**Comment by Turbo87** [comment]
just had a more detailed look. nice work @Joey9801! I've opened a few issues on the things that I noticed, but in general, this looks quite cool.

I was struggling a little in https://github.com/Turbo87/rust-igc because I couldn't decide whether to go for a low-level or high-level parser. the correct handling of I/J records makes it somewhat annoying...
